contact_links:
  - name: â— å®‰å…¨æ€§å•é¡Œ
    url: https://zh.wikipedia.org/wiki/è´Ÿè´£ä»»çš„æŠ«éœ²
    about:
      ä¸è¦é€é issue æˆ–å…¬é–‹è¨è«–èªªæ˜ä»»ä½•å®‰å…¨æ€§å•é¡Œã€‚å˜—è©¦é€éç§å¯†æ–¹å¼å’Œåœ˜éšŠè² è²¬äººè¯çµ¡ï¼Œä¾‹å¦‚ä¿¡ç®±ï¼ˆevanlu361425@gmail.comï¼‰ã€‚
      æˆ‘å€‘æœƒä¸€èµ·è¨è«–å’Œè§£æ±ºé€™é¡å•é¡Œï¼Œæ„Ÿè¬ï¼
  - name: ğŸ‘» å…¶ä»–
    url: https://github.com/evan361425/flutter-pos-system/discussions
    about: å…¶ä»–æ‰€æœ‰å•é¡Œéƒ½å¯ä»¥æå‡ºä¾†è¨è«–
